name: Build Qt

on:
  push:
    branches:
      - main
      - release/*
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: 5.15.2
      - name: qmake
        run: qmake
        working-directory: Qt
      - name: make
        run: make
        working-directory: Qt
      - name: list files
        run: ls 
        working-directory: Qt 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: medifier-linux-build
          path: Qt/mEDIFIER
    
